version: '3'
services:
  backend:
    build: backend/
    image: korp_backend_base

  # NOTE: lacks an entrypoint - extend korp_frontend_base in separate Dockerfile
  frontend:
    build: frontend/
    image: korp_frontend_base
