FROM ubuntu:jammy

RUN echo cachebreakerr
RUN mkdir guides
COPY ./userguides /userguides

# Uncomment in order to be able to enter the running container using
# docker-compose exec docs bash.
#CMD sleep infinity
