// Generated by scripts/modejs2yaml.js: functions that were inline in the old mode
// files, now referenced by name from stats_stringify / stats_cqp in the corpus YAML.
export default {
    joinWithSpace: (values) => values.join(" "),
}
