// Generated by scripts/modejs2yaml.js: sidebar value stringifiers referenced by
// name from `stringify` in the corpus YAML.
import { Lemgram } from "@/lemgram"
export default {
    prefix: (lemgram) => Lemgram.parse(lemgram)?.toString() || lemgram,
}
