version: '3'
services:
  backend:
    build: ../../backend
    # fixes race condition https://vsupalov.com/simple-fix-db-not-ready/
    restart: on-failure
    volumes:
      - /Users/phb514/mygit/korp-setups/setups/memotest/corpora/ 
#     - /Users/rqf595/Desktop/korp-old/korp-corpora:/opt/corpora
#      - /opt/corpora:/opt/corpora
    ports:
      # Korp backend server
      - "1234:1234"
  frontend:
    build: frontend/
    restart: on-failure
    depends_on:
      - backend
    ports:
      # Korp frontend server
      - "9111:9111"
