version: '3'
services:
  doc:
    build: ../../doc/
    image: korp_docs
  backend:
    build: ../../backend
    # fixes race condition https://vsupalov.com/simple-fix-db-not-ready/
    restart: on-failure
    volumes:
      - ./corpora:/opt/corpora
    ports:
      # Korp backend server
      - "11234:1234"
  frontend:
    build: frontend/
    restart: on-failure
    depends_on:
      - doc
      - backend
    ports:
      # Korp frontend server
      - "19111:9111"
  partitur:
    build: partitur/
    restart: on-failure
    volumes:
      # DB_PATH=/Users/phb514/custom_software/parse_textgrids/output docker-compose up -d --build
      # Win PowerShell: $env:DB_PATH='C:\custom_software\parse_textgrids\output' ; docker-compose up -d --build
      - $DB_PATH:/opt/output
      - $AUDIO_DIR:/opt/audio
    ports:
      # "Partitur" view server
      # <host port>:<docker port>! 5000: Flask app default port
      - "15005:5000"
